# API Binding configuration
# This can sit behind a reverse proxy
host: "0.0.0.0"
port: 1025

# Log ip on request
logIp: True

# Endpoint configuration
email_ratelimit: "3/minutes" # This translates to 3 requests per minute from the same IP
subscription_ratelimit: "1/hours"

# this is an example secret key, please change this if you're using this configuration as a reference
secret_key: "3w!5%cl(h%82chrcda@6vin-nn%@zy8r!rx%i0vy7$o_j@w-5t"

# Email configuration
# Only supports starttls (port 587)
mail_host: "smtp.hostinger.com"
mail_port: 587 # Don't change, even if provider does not use tls, the protocol will handle it
mail_username: "contact@sembleit.ro"

# Placeholders
# Below placeholders will be parsed in templates
# and will be replaced with values from the post request body
placeholders: ["%name%", "%subject%", "%from%", "%message%", "%phone%", "%email%"]
# Custom placeholders can be set in recipient_map config for each customer
# They will be replaced in the template using key-value pairs set in recipient map
custom_placeholders: ["%friendly_name%"]